const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',

    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //admin
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILDED: 'FETCH_GENDER_FAILDED',

    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAILDED: 'FETCH_POSITION_FAILDED',

    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILDED: 'FETCH_ROLE_FAILDED',

    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILDED: 'CREATE_USER_FAILDED',

    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILDED: 'EDIT_USER_FAILDED',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILDED: 'DELETE_USER_FAILDED',

    FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
    FETCH_ALL_USERS_FAILDED: 'FETCH_ALL_USERS_FAILDED',

    FETCH_ALL_MANAGERS_SUCCESS: 'FETCH_ALL_MANAGERS_SUCCESS',
    FETCH_ALL_MANAGERS_FAILDED: 'FETCH_ALL_MANAGERS_FAILDED',

    SAVE_BASIC_SALARY_SUCCESS: 'SAVE_BASIC_SALARY_SUCCESS',
    SAVE_BASIC_SALARY_FAILDED: 'SAVE_BASIC_SALARY_FAILDED',

    CREATE_EVENT_SUCCESS: 'CREATE_EVENT_SUCCESS',
    CREATE_EVENT_FAILDED: 'CREATE_EVENT_FAILDED',

    EDIT_EVENT_SUCCESS: 'EDIT_EVENT_SUCCESS',
    EDIT_EVENT_FAILDED: 'EDIT_EVENT_FAILDED',

    DELETE_EVENT_SUCCESS: 'DELETE_EVENT_SUCCESS',
    DELETE_EVENT_FAILDED: 'DELETE_EVENT_FAILDED',

    FETCH_ALL_EVENTS_SUCCESS: 'FETCH_ALL_EVENTS_SUCCESS',
    FETCH_ALL_EVENTS_FAILDED: 'FETCH_ALL_EVENTS_FAILDED',
})

export default actionTypes;